language: python
python:
  - 3.7
before_install:
  - pip install --upgrade pip
  # to interact with codecov
  - pip install codecov
install:
  # include extras_require test
  - pip install ".[test]"
script:
  - pytest tests/ --cov=viennaRNA
# push the results to codecov
after_success:
  - codecov